<a href="https://colab.research.google.com/github/AbhishekRP2002/Tensorflow-2.0-Learning/blob/main/TensorFlow_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TensorFlow operates on multidimensional arrays or tensors represented as tf.Tensor objects.
- Tensors are the basic data structures or building blocks of TensorFlow.
- Tensors are identified by the following parameters:

1.   Rank
2.   Shape
3.   Type




The name “TensorFlow” might make more sense because deep learning models are essentially a flow of tensors through operations from input to output.

- Tensor.shape : tells the size of the tensor along each of its axes.
- Tensor.dtype : tells the datatype of the elements used in the tensor object 
- Tensors are immutable 

In [ ]:
import tensorflow as tf

In [ ]:
#Initialization of tensorflow Tensors
# x = tf.constant([tensor list] , shape=(m ,n) , dtype=int32 / float32 / any other datatype)


x =tf.constant( [[1,2,3,] ,
                 [2,4,7]])
print(x.shape)
print(x.dtype)
print(2*x)

print("\n")
y = tf.ones((2,2)) #specifying the shape of the tensor
z = tf.zeros((2,2))
m = tf.eye(3) # I for identity matrix
print(m)
print(y)
print(z)
print("\n")
x1 = tf.random.normal((3,3) , mean = 0, stddev = 1) #stddev stands for standard deviation 
x2= tf.random.uniform((3,3) , minval =0, maxval =1) # uniform distribution
print(x1)
print(x2)
print("\n")
x3 = tf.range(10)
print(x3)
print("\n")
x4 = tf.range(start=1 , limit=10 , delta =2) #delta  is difference or steps 
print(x4)

(2, 3)
<dtype: 'int32'>
tf.Tensor(
[[ 2  4  6]
 [ 4  8 14]], shape=(2, 3), dtype=int32)


tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


tf.Tensor(
[[-0.49584502 -2.125813   -0.11987344]
 [ 2.071792   -0.6374647  -0.6703832 ]
 [ 0.7105538   1.9368589   0.9934502 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.3573084  0.5553037  0.22913325]
 [0.7498013  0.27326894 0.74014044]
 [0.59979165 0.987007   0.04010999]], shape=(3, 3), dtype=float32)


tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


## Mathematical operations on tensors

Tensors operations are similar to numpy arrays

In [ ]:

 yw = tf.constant([1., 3., 5.] , dtype = 'float32')
 zw = tf.constant([1.,3.,5.] , dtype = 'float32')

 sum_var = tf.add(x, y)
 print(sum_var)
 print("\n")
 prod_var = tf.multiply(x, y)
 print(prod_var)
 print("\n")



IndentationError: ignored

In [ ]:
tf.transpose(x)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 4],
       [3, 7]], dtype=int32)>

In [ ]:
tf.concat([x , x , x] , axis =0)

<tf.Tensor: shape=(6, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 4, 7],
       [1, 2, 3],
       [2, 4, 7],
       [1, 2, 3],
       [2, 4, 7]], dtype=int32)>

In [ ]:
 k = tf.concat([x , x , x] , axis =1)
 print(k)

tf.Tensor(
[[1 2 3 1 2 3 1 2 3]
 [2 4 7 2 4 7 2 4 7]], shape=(2, 9), dtype=int32)


In [ ]:
m = tf.constant([1,2,3 ])
n = tf.constant([1,2,3])
z1 = tf.tensordot(x , y , axes=1)
print(z1)
z2 = tf.reduce_sum(x*y , axes=0)
print( z2 )

InvalidArgumentError: ignored



```
 tf.math.reduce_sum(
    input_tensor, axis=None, keepdims=False, name=None
)
```
It computes the sum of elements along a given dimension of a tensor


In [ ]:
x = tf.constant([[1,1,1,] , [1,1,1]])
x.numpy()
x1 = tf.reduce_sum(x).numpy()
print(x1)

6


In [ ]:
# reduce along the first dimension
x2 = tf.reduce_sum(x , 0).numpy()
print(x2)

[2 2 2]


In [ ]:
# reduce along the second dimension
x3 = tf.reduce_sum(x , 1).numpy()
print(x3)

[3 3]


In [ ]:
# reduce along the both dimensions
x4 = tf.reduce_sum(x , [0 ,1]).numpy()
print(x4)

6


In [ ]:
y = tf.constant([[1,1,1,] , [1,1,1]])
y1 =tf.reduce_sum(y , 0)
print(y1)

tf.Tensor([2 2 2], shape=(3,), dtype=int32)




```
tf.tensordot(
    a, b, axes, name=None
)
```
Tensor contraction of a and b along specified axes and outer product.Tensordot (also known as tensor contraction) sums the product of elements from a and b over the indices specified by axes.


In [ ]:
a = tf.constant([[2,1,1,] ,
                 [1,3,1]])
b = tf.constant([[1,1,1,] , 
                 [1,1,1]])
c = tf.tensordot(a , b , axes = 0)
print(c)

tf.Tensor(
[[[[2 2 2]
   [2 2 2]]

  [[1 1 1]
   [1 1 1]]

  [[1 1 1]
   [1 1 1]]]


 [[[1 1 1]
   [1 1 1]]

  [[3 3 3]
   [3 3 3]]

  [[1 1 1]
   [1 1 1]]]], shape=(2, 3, 2, 3), dtype=int32)


In [ ]:
from numpy import power
powerans = a ** 5
print(powerans)

tf.Tensor(
[[ 32   1   1]
 [  1 243   1]], shape=(2, 3), dtype=int32)


### Matrix multiplication using matmul function 

In [ ]:

import tensorflow as tf
a = tf.constant([[2,1,1,] ,
                 [1,3,1]])
b = tf.constant([[1,1] , 
                 [1,1],
                 [1,1]])
ans = tf.matmul(a , b)
print(ans)
ans = a @ b
print(ans)


tf.Tensor(
[[4 4]
 [5 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[4 4]
 [5 5]], shape=(2, 2), dtype=int32)


**Indexing in Tensors is same as numpy arrays**

In [ ]:
x  = tf.range(10)
print(x[:])
print(x[1:])
print(x[1: 4])
print(x[::2]) #gap of 1 
print(x[::-1]) #reversde order 

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)
tf.Tensor([9 8 7 6 5 4 3 2 1 0], shape=(10,), dtype=int32)


In [ ]:
a = tf.constant([[2,1,1,] ,
                 [1,3,1]])
print(a[0])
print(a[0 , :])
print(a[:,])

tf.Tensor([2 1 1], shape=(3,), dtype=int32)
tf.Tensor([2 1 1], shape=(3,), dtype=int32)
tf.Tensor(
[[2 1 1]
 [1 3 1]], shape=(2, 3), dtype=int32)


**Reshaping in Tf**

In [ ]:
x = tf.range(9)
x_r = tf.reshape(x , (3,3))  #First parameter is the tensor object you aim to reshape and the second parameter i the shape into which u want to reshape 
print(x_r)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


# TensorFlow Graphs and Functions

This part will show how graphs are stored in Tensorflow , and represented in it, how we can use them tyo accelerate our model.
-   tf.function allows you to switch from eager execution to graph execution.
- Eager execution vs Graph execution


1.   **Eager execution**: Tensortflow operations are executed by python opertion by operation , returning results back to python
2.   **Graph execution**: Graph execution means that tensor computations are executed as a TensorFlow graph, sometimes referred to as a tf.Graph or simply a "graph."





---
Graphs are data structures that contain a set of tf.Operation objects, which represent units of computation; and tf.Tensor objects, which represent the units of data that flow between operations. They are defined in a tf.Graph context. Since these graphs are data structures, they can be saved, run, and restored all without the original Python code.


### Graph Advanatges:
- In short, graphs are extremely useful and let your TensorFlow run fast, run in parallel, and run efficiently on multiple devices.
- With a graph, you have a great deal of flexibility. You can use your TensorFlow graph in environments that don't have a Python interpreter, like mobile applications, embedded devices, and backend servers. TensorFlow uses graphs as the format for saved models when it exports them from Python.

## Neural Networks with Sequential and Functional API

In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

Check this out for better understandng  :[Model building with tf.keras](https://medium.com/deep-learning-demystified/tensorflow-2-model-building-with-tf-keras-1a9b050373ed)

[Understanding Sequential Vs Functional API in Keras](https://www.analyticsvidhya.com/blog/2021/07/understanding-sequential-vs-functional-api-in-keras/)

**SequentialAPI:**
When to use?
- A basic NN consists of a input layer , an hidden layer and a output layer . If hidden layer is absent , then it's called a Perceptron.
- In Seq. API , we create the model layer by layer .Itis very simple , convinient yet not flexible.
- A Sequential model is not appropriate when:

1. Your model has multiple inputs or multiple outputs
2. Any of your layers has multiple inputs or multiple outputs
3. You need to do layer sharing
4. You want non-linear topology (e.g. a residual connection, a multi-branch model)
- **A Sequential model is appropriate for a plain stack of layers where each layer has exactly one input tensor and one output tensor.**

In [3]:
from tensorflow.keras.datasets import mnist

In [4]:
#Working with the MNIST dataset
(x_train , y_train) , (x_test , y_test) = mnist.load_data()
print(x_train.shape)
print(y_train.shape)



11501568/11490434 [==============================] - 0s 0us/step
(60000, 28, 28)
(60000,)


In [25]:
#we have to flatten the multi-dimensional input 
x_train = x_train.reshape(-1 , 28*28)
x_test = x_test.reshape(-1, 28*28)
print(x_train.shape)

# Preprocess the data (these are NumPy arrays)
x_train = x_train.reshape(60000, 784).astype("float32") / 255
x_test = x_test.reshape(10000, 784).astype("float32") / 255

y_train = y_train.astype("float32")
y_test = y_test.astype("float32")
print(x_train.shape)
print(x_train[:10])




(60000, 784)
(60000, 784)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [11]:
#  Define the model
model = keras.Sequential([
         layers.Dense(512 , activation = 'relu'),
         layers.Dense(256 , activation = 'relu'),
         layers.Dense(10), 
])
# model.summary() (You can't do this also)
# At this point, you can't do this:
# model.weights

ValueError: ignored

In [10]:
model1 = tf.keras.Sequential([
         keras.layers.Dense(512 , activation = 'relu'),
         keras.layers.Dense(256 , activation = 'relu'),
         keras.layers.Dense(10), 
])  # same as model in above block

In [12]:
model.layers

You can also create a Sequential model incrementally via the add() method:

In [14]:
model2 = tf.keras.Sequential()
model2.add(layers.Dense(512 , activation = 'relu'))
model2.add(layers.Dense(256 , activation ='relu'))
model2.add(layers.Dense(10))
#In this method we can use model.summary( ) after addition of each layer , which can come handy while  dealing with complex models 

Note that there's also a corresponding pop() method to remove layers: a Sequential model behaves very much like a list of layers.

In [15]:
model2.pop()
print(len(model2.layers))

2


# Note:
All layers in Keras need to know about the shape of theiriunputs in order to be able to create weights .Naturally, this also applies to Sequential models. When you instantiate a Sequential model without an input shape, it isn't "built": it has no weights (and calling model.weights results in an error stating just this). The weights are created when the model first sees some input data:

In [19]:
model = keras.Sequential([
         layers.Input(shape = (784)),
         layers.Dense(512 , activation = 'relu'),
         layers.Dense(256 , activation = 'relu'),
         layers.Dense(10), 
])
# Note that Input object is not a part of model.layers as it is not a layer
model.summary() 
print(len(model.weights))

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_24 (Dense)            (None, 512)               401920    
                                                                 
 dense_25 (Dense)            (None, 256)               131328    
                                                                 
 dense_26 (Dense)            (None, 10)                2570      
                                                                 
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
6


A simple alternative is to just pass an `input_shape` argument to your first layer:

In [34]:
# model = keras.Sequential([
#          layers.Dense(512 , activation = 'relu' , input_shape=(28,28,1)),
#          layers.Dense(256 , activation = 'relu'),
#          layers.Dense(10), 
# ])

# model = keras.Sequential([
#          layers.Dense(512 , activation = 'relu' , input_shape=(28,28)),
#          layers.Dense(256 , activation = 'relu'),
#          layers.Dense(10), 
# ])

model = keras.Sequential([
         layers.Dense(512 , activation = 'relu' , input_shape=(784,)),
         layers.Dense(256 , activation = 'relu'),
         layers.Dense(10 , activation='softmax'), 
]) 




In [35]:
#Specifying the training config
model.compile(
    optimizer = keras.optimizers.Adam(lr=0.001),
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=["accuracy"],
)
model.summary()

Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_39 (Dense)            (None, 512)               401920    
                                                                 
 dense_40 (Dense)            (None, 256)               131328    
                                                                 
 dense_41 (Dense)            (None, 10)                2570      
                                                                 
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


In [36]:
print("Fit model on training data")
model.fit(x_train , y_train ,batch_size=32, epochs=5 , verbose=2)
# Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = model.evaluate(x_test, y_test, batch_size=32 , verbose =2)
print("test loss, test acc:", results)

Fit model on training data
Epoch 1/5


/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1082: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  return dispatch_target(*args, **kwargs)


1875/1875 - 4s - loss: 2.3016 - accuracy: 0.1117 - 4s/epoch - 2ms/step
Epoch 2/5
1875/1875 - 3s - loss: 2.3014 - accuracy: 0.1124 - 3s/epoch - 2ms/step
Epoch 3/5
1875/1875 - 3s - loss: 2.3013 - accuracy: 0.1124 - 3s/epoch - 2ms/step
Epoch 4/5
1875/1875 - 4s - loss: 2.3008 - accuracy: 0.1124 - 4s/epoch - 2ms/step
Epoch 5/5
1875/1875 - 3s - loss: 2.2945 - accuracy: 0.1227 - 3s/epoch - 2ms/step
Evaluate on test data
313/313 - 1s - loss: 2.2815 - accuracy: 0.1184 - 633ms/epoch - 2ms/step
test loss, test acc: [2.2814724445343018, 0.11840000003576279]


**Functional API:**


In [38]:
inputs = keras.Input(shape=(784))
x= layers.Dense(512 , activation = 'relu')(inputs)
x = layers.Dense(256 , activation = 'relu')(x)
outputs = layers.Dense(10 , activation = 'softmax')(x)
model = keras.Model(inputs =inputs , outputs = outputs)

model.compile(
    optimizer = keras.optimizers.Adam(lr=0.001),
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    metrics=["accuracy"],
)
model.summary()
model.fit(x_train , y_train ,batch_size=32, epochs=5 , verbose=2)
# Evaluate the model on the test data using `evaluate`
print("Evaluate on test data")
results = model.evaluate(x_test, y_test, batch_size=32 , verbose =2)
print("test loss, test acc:", results)



Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_6 (InputLayer)        [(None, 784)]             0         
                                                                 
 dense_45 (Dense)            (None, 512)               401920    
                                                                 
 dense_46 (Dense)            (None, 256)               131328    
                                                                 
 dense_47 (Dense)            (None, 10)                2570      
                                                                 
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


Epoch 1/5
1875/1875 - 7s - loss: 2.3016 - accuracy: 0.1119 - 7s/epoch - 4ms/step
Epoch 2/5
1875/1875 - 4s - loss: 2.3014 - accuracy: 0.1124 - 4s/epoch - 2ms/step
Epoch 3/5
1875/1875 - 3s - loss: 2.3013 - accuracy: 0.1124 - 3s/epoch - 2ms/step
Epoch 4/5
1875/1875 - 3s - loss: 2.3012 - accuracy: 0.1124 - 3s/epoch - 2ms/step
Epoch 5/5
1875/1875 - 3s - loss: 2.3005 - accuracy: 0.1124 - 3s/epoch - 2ms/step
Evaluate on test data
313/313 - 1s - loss: 2.2989 - accuracy: 0.1135 - 638ms/epoch - 2ms/step
test loss, test acc: [2.298935651779175, 0.11349999904632568]


**The low accuracy is cuz the softmax function is not reflected in the output**

In [39]:
from google.colab import files
from IPython.display import Image

In [40]:
uploaded = files.upload()